In [22]:
import os
import subprocess
import sys
import json
import pandas as pd

In [23]:
run_iteration = 10
pwd = os.getcwd()
build_dir = os.path.join(pwd, "build")

In [24]:
def run(cmd, cwd=None) -> str:
    """Run a command and exit on failure (like set -e)."""
    print(f"+ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, check=True, capture_output=True, text=True)
    return result.stdout

In [25]:
def analysis_code(key, data_tag) -> dict:
    binary_path = os.path.join(build_dir, f"power_meter_{key}")
    program_results = []
    if os.path.isfile(binary_path):
        print("\n" + "=" * 102)
        print(f"Analyzing for {key} ...")

        # Match bash loop: for i in {1..1}
        for i in range(0, run_iteration):
            if data_tag:
                data_file = os.path.join(
                    pwd, f"power_meter_{data_tag}_data.bin"
                )
                
                result = subprocess.run([binary_path, data_file], cwd=None, check=True, capture_output=True, text=True)
            else:
                result = subprocess.run([binary_path], cwd=None, check=True, capture_output=True, text=True)
            program_results.append(json.loads(result.stdout))


        # size binary
        result = run(["size", binary_path])
        lines = result.strip().splitlines()

        headers = lines[0].split()
        values = lines[1].split(maxsplit=len(headers) - 1)

        size_dict = dict(zip(headers, values))
        
        analysis_result = {"key":key,"program_results": program_results, "size_results": size_dict}
        return analysis_result

    else:
        raise ValueError(f"Error: Program {binary_path} not found!")

In [26]:
def analysis_deserialization(results: dict, id: str):
    rows = []

    overhead = results['overhead_deserialization']["program_results"]
    overhead_time_taken = sum(r["time_taken"] for r in overhead)/ len([r["time_taken"] for r in overhead])
    overhead_buffer_size = sum(r["buffer_size"] for r in overhead)/ len([r["buffer_size"] for r in overhead])
    overhead_flash_text = int(results['overhead_deserialization']['size_results']['text'])
    overhead_static_ram = (
                   int(results['overhead_deserialization']['size_results']["data"])
                    + int(results['overhead_deserialization']['size_results']["bss"])
                )
    for key, program in results.items():
        if id in key:
            times = [r["time_taken"] for r in program["program_results"]]
            buffers = [r["buffer_size"] for r in program["program_results"]]

            rows.append({
                "id": key,
                # "avg_time_taken": sum(times) / len(times),
                # "min_time": min(times),
                # "max_time": max(times),
                # "buffer_size": (sum(buffers) / len(buffers)),
                # "flash_text": program["size_results"]["text"],
                # "static_ram": (
                #    int( program["size_results"]["data"])
                #     + int(program["size_results"]["bss"])
                # ),
                "avg_time_taken_net": (sum(times) / len(times)) - overhead_time_taken,
                "min_time_net": min(times) - overhead_time_taken,
                "max_time_net": max(times) - overhead_time_taken,
                "buffer_size_net": buffers[0] - overhead_buffer_size,
                "flash_text_net": int(program["size_results"]["text"]) - overhead_flash_text,
                "static_ram_net": (
                   int( program["size_results"]["data"])
                    + int(program["size_results"]["bss"])
                ) - overhead_static_ram,
            })

    df = pd.DataFrame(rows)
    print(df.to_latex())
    return df

In [27]:
def analysis_serialization(results: dict, id: str):
    rows = []

    overhead = results['overhead_serialization']["program_results"]
    overhead_time_taken = sum(r["time_taken"] for r in overhead)/ len([r["time_taken"] for r in overhead])
    overhead_buffer_size = sum(r["buffer_size"] for r in overhead)/ len([r["buffer_size"] for r in overhead])
    overhead_flash_text = int(results['overhead_serialization']['size_results']['text'])
    overhead_static_ram = (
                   int(results['overhead_serialization']['size_results']["data"])
                    + int(results['overhead_serialization']['size_results']["bss"])
                )
    for key, program in results.items():
        if id in key:
            times = [r["time_taken"] for r in program["program_results"]]
            buffers = [r["buffer_size"] for r in program["program_results"]]

            rows.append({
                "id": key,
                # "avg_time_taken": sum(times) / len(times),
                # "min_time": min(times),
                # "max_time": max(times),
                # "buffer_size": (sum(buffers) / len(buffers)),
                # "flash_text": program["size_results"]["text"],
                # "static_ram": (
                #    int( program["size_results"]["data"])
                #     + int(program["size_results"]["bss"])
                # ),
                "avg_time_taken_net": (sum(times) / len(times)) - overhead_time_taken,
                "min_time_net": min(times) - overhead_time_taken,
                "max_time_net": max(times) - overhead_time_taken,
                "buffer_size_net": buffers[0] - overhead_buffer_size,
                "flash_text_net": int(program["size_results"]["text"]) - overhead_flash_text,
                "static_ram_net": (
                   int( program["size_results"]["data"])
                    + int(program["size_results"]["bss"])
                ) - overhead_static_ram,
            })

    df = pd.DataFrame(rows)
    print(df.to_latex())
    return df

In [28]:
program_results = {}
def main():
    # Configure and build
    run(["cmake", "-S", ".", "-B", "build"])
    run(["cmake", "--build", "build", "-j12"])

    # Program map (ordered like bash associative array is NOT guaranteed,
    # but Python 3.7+ dict preserves insertion order)
    programs = {
        "overhead_deserialization": "overhead",

        "nakedbytes_deserialization_without_access": "nakedbytes",
        "nakedbytes_deserialization_with_one_access": "nakedbytes",
        "nakedbytes_deserialization_with_all_access": "nakedbytes",

        "flatbuffers_deserialization_without_access": "flatbuffers",
        "flatbuffers_deserialization_with_one_access": "flatbuffers",
        "flatbuffers_deserialization_with_all_access": "flatbuffers",

        "protobuf_deserialization_without_access": "protobuf",
        "protobuf_deserialization_with_one_access": "protobuf",
        "protobuf_deserialization_with_all_access": "protobuf",

        "nanopb_deserialization_without_access": "protobuf",
        "nanopb_deserialization_with_one_access": "protobuf",
        "nanopb_deserialization_with_all_access": "protobuf",

        "overhead_serialization": "",

        "nakedbytes_serialization_primitives": "",
        "nakedbytes_serialization_all": "",

        "flatbuffers_serialization_primitives": "",
        "flatbuffers_serialization_all": "",

        "protobuf_serialization_primitives": "",
        "protobuf_serialization_all": "",

        "nanopb_serialization_primitives": "",
        "nanopb_serialization_all": "",
    }

    for key, data_tag in programs.items():
       program_results[key] = analysis_code(key=key, data_tag= data_tag)
    print(json.dumps(program_results,indent = 2 ))

In [29]:
main()

+ cmake -S . -B build
+ cmake --build build -j12

======================================================================================================
Analyzing for overhead_deserialization ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_overhead_deserialization

======================================================================================================
Analyzing for nakedbytes_deserialization_without_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nakedbytes_deserialization_without_access

======================================================================================================
Analyzing for nakedbytes_deserialization_with_one_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nakedbytes_deserialization_with_one_access

======================================================================================================
Analyzing for nakedbytes_deserialization_with_all_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nakedbytes_deserialization_with_all_access

======================================================================================================
Analyzing for flatbuffers_deserialization_without_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_flatbuffers_deserialization_without_access

======================================================================================================
Analyzing for flatbuffers_deserialization_with_one_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_flatbuffers_deserialization_with_one_access

======================================================================================================
Analyzing for flatbuffers_deserialization_with_all_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_flatbuffers_deserialization_with_all_access

======================================================================================================
Analyzing for protobuf_deserialization_without_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_protobuf_deserialization_without_access

======================================================================================================
Analyzing for protobuf_deserialization_with_one_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_protobuf_deserialization_with_one_access

======================================================================================================
Analyzing for protobuf_deserialization_with_all_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_protobuf_deserialization_with_all_access

======================================================================================================
Analyzing for nanopb_deserialization_without_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nanopb_deserialization_without_access

======================================================================================================
Analyzing for nanopb_deserialization_with_one_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nanopb_deserialization_with_one_access

======================================================================================================
Analyzing for nanopb_deserialization_with_all_access ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nanopb_deserialization_with_all_access

======================================================================================================
Analyzing for overhead_serialization ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_overhead_serialization

======================================================================================================
Analyzing for nakedbytes_serialization_primitives ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nakedbytes_serialization_primitives

======================================================================================================
Analyzing for nakedbytes_serialization_all ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nakedbytes_serialization_all

======================================================================================================
Analyzing for flatbuffers_serialization_primitives ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_flatbuffers_serialization_primitives

======================================================================================================
Analyzing for flatbuffers_serialization_all ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_flatbuffers_serialization_all

======================================================================================================
Analyzing for protobuf_serialization_primitives ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_protobuf_serialization_primitives

======================================================================================================
Analyzing for protobuf_serialization_all ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_protobuf_serialization_all

======================================================================================================
Analyzing for nanopb_serialization_primitives ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nanopb_serialization_primitives

======================================================================================================
Analyzing for nanopb_serialization_all ...
+ size /home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nanopb_serialization_all
{
  "overhead_deserialization": {
    "key": "overhead_deserialization",
    "program_results": [
      {
        "iteration": 100000,
        "time_taken": 215,
        "buffer_size": 0
      },
      {
        "iteration": 100000,
        "time_taken": 215,
        "buffer_size": 0
      },
      {
        "iteration": 100000,
        "time_taken": 215,
        "buffer_size": 0
      },
      {
        "iteration": 100000,
        "time_taken": 284,
        "buffer_size": 0
      },
      {
        "iteration": 100000,
        "time_taken": 215,
        "buffer_size": 0
      },
      {
        "iteration": 100000,
        "time_taken": 215,
        "buffer_size": 0
      },
      {
        "iteration": 100000,
        "time_taken": 215,
        "buffer_size": 0
      },
      {
        "iteration": 100000,
        "time_taken": 471,
        "buffer_size": 0
      },
      {
        "iteration": 100000,
        "time_taken": 215,
        "buffer_size": 0
      },
      {
        "iteration": 100000,
        "time_taken": 215,
        "buffer_size": 0
      }
    ],
    "size_results": {
      "text": "4439",
      "data": "672",
      "bss": "8",
      "dec": "5119",
      "hex": "13ff",
      "filename": "/home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_overhead_deserialization"
    }
  },
  "nakedbytes_deserialization_without_access": {
    "key": "nakedbytes_deserialization_without_access",
    "program_results": [
      {
        "iteration": 100000,
        "time_taken": 245,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 253,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 255,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 236,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 235,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 241,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 239,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 353,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 235,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 235,
        "buffer_size": 72
      }
    ],
    "size_results": {
      "text": "4452",
      "data": "672",
      "bss": "8",
      "dec": "5132",
      "hex": "140c",
      "filename": "/home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nakedbytes_deserialization_without_access"
    }
  },
  "nakedbytes_deserialization_with_one_access": {
    "key": "nakedbytes_deserialization_with_one_access",
    "program_results": [
      {
        "iteration": 100000,
        "time_taken": 589,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 592,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 614,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 660,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 619,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 708,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 631,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 583,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 739,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 628,
        "buffer_size": 72
      }
    ],
    "size_results": {
      "text": "5153",
      "data": "680",
      "bss": "8",
      "dec": "5841",
      "hex": "16d1",
      "filename": "/home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nakedbytes_deserialization_with_one_access"
    }
  },
  "nakedbytes_deserialization_with_all_access": {
    "key": "nakedbytes_deserialization_with_all_access",
    "program_results": [
      {
        "iteration": 100000,
        "time_taken": 2749,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 3666,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 2523,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 2842,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 2488,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 2529,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 2537,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 2566,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 2683,
        "buffer_size": 72
      },
      {
        "iteration": 100000,
        "time_taken": 3804,
        "buffer_size": 72
      }
    ],
    "size_results": {
      "text": "7361",
      "data": "688",
      "bss": "8",
      "dec": "8057",
      "hex": "1f79",
      "filename": "/home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_nakedbytes_deserialization_with_all_access"
    }
  },
  "flatbuffers_deserialization_without_access": {
    "key": "flatbuffers_deserialization_without_access",
    "program_results": [
      {
        "iteration": 100000,
        "time_taken": 1606,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 2215,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 1907,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 1961,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 2153,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 1723,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 1547,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 1616,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 1639,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 1545,
        "buffer_size": 108
      }
    ],
    "size_results": {
      "text": "5186",
      "data": "688",
      "bss": "8",
      "dec": "5882",
      "hex": "16fa",
      "filename": "/home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_flatbuffers_deserialization_without_access"
    }
  },
  "flatbuffers_deserialization_with_one_access": {
    "key": "flatbuffers_deserialization_with_one_access",
    "program_results": [
      {
        "iteration": 100000,
        "time_taken": 5552,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 5291,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 4972,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 5653,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 5160,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 5802,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 5191,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 5487,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 6243,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 5264,
        "buffer_size": 108
      }
    ],
    "size_results": {
      "text": "6413",
      "data": "688",
      "bss": "8",
      "dec": "7109",
      "hex": "1bc5",
      "filename": "/home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_flatbuffers_deserialization_with_one_access"
    }
  },
  "flatbuffers_deserialization_with_all_access": {
    "key": "flatbuffers_deserialization_with_all_access",
    "program_results": [
      {
        "iteration": 100000,
        "time_taken": 36436,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 37177,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 38302,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 36563,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 36128,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 34663,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 36495,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 34289,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 35957,
        "buffer_size": 108
      },
      {
        "iteration": 100000,
        "time_taken": 33898,
        "buffer_size": 108
      }
    ],
    "size_results": {
      "text": "8912",
      "data": "696",
      "bss": "8",
      "dec": "9616",
      "hex": "2590",
      "filename": "/home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_flatbuffers_deserialization_with_all_access"
    }
  },
  "protobuf_deserialization_without_access": {
    "key": "protobuf_deserialization_without_access",
    "program_results": [
      {
        "iteration": 100000,
        "time_taken": 40503,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 37390,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 38123,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 38838,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 40774,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 39426,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 38675,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 38694,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 37593,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 41340,
        "buffer_size": 66
      }
    ],
    "size_results": {
      "text": "2764956",
      "data": "40072",
      "bss": "114484",
      "dec": "2919512",
      "hex": "2c8c58",
      "filename": "/home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_protobuf_deserialization_without_access"
    }
  },
  "protobuf_deserialization_with_one_access": {
    "key": "protobuf_deserialization_with_one_access",
    "program_results": [
      {
        "iteration": 100000,
        "time_taken": 38604,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 37707,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 36056,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 36899,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 41519,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 39512,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 41466,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 44481,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 37492,
        "buffer_size": 66
      },
      {
        "iteration": 100000,
        "time_taken": 40508,
        "buffer_size": 66
      }
    ],
    "size_results": {
      "text": "2765752",
      "data": "40080",
      "bss": "114484",
      "dec": "2920316",
      "hex": "2c8f7c",
      "filename": "/home/busoye_tm/Documents/matthew/projects/nakedbytes/research_experiment/power_meter/build/power_meter_protobuf_deserialization_with_one_access"
    }
  },
  "protobuf_deserialization_with_all_access": {
    "key": "protobuf_deserialization_with_all_access",
    "program_results": [
      {
        "iteration": 100000,
        "time_taken": 49861,
        "buffer_size": 66
      },
      {
        "iteration": 100000,

In [30]:

analysis_deserialization(program_results, "deserialization_without_access")

\begin{tabular}{llrrrrrr}
\toprule
 & id & avg_time_taken_net & min_time_net & max_time_net & buffer_size_net & flash_text_net & static_ram_net \\
\midrule
0 & nakedbytes_deserialization_without_access & 5.200000 & -12.500000 & 105.500000 & 72.000000 & 13 & 0 \\
1 & flatbuffers_deserialization_without_access & 1543.700000 & 1297.500000 & 1967.500000 & 108.000000 & 747 & 16 \\
2 & protobuf_deserialization_without_access & 38888.100000 & 37142.500000 & 41092.500000 & 66.000000 & 2760517 & 153876 \\
3 & nanopb_deserialization_without_access & 137538.100000 & 121419.500000 & 163266.500000 & 66.000000 & 16656 & 64 \\
\bottomrule
\end{tabular}

,id,avg_time_taken_net,min_time_net,max_time_net,buffer_size_net,flash_text_net,static_ram_net
0,nakedbytes_deserialization_without_access,5.2,-12.5,105.5,72.0,13,0
1,flatbuffers_deserialization_without_access,1543.7,1297.5,1967.5,108.0,747,16
2,protobuf_deserialization_without_access,38888.1,37142.5,41092.5,66.0,2760517,153876
3,nanopb_deserialization_without_access,137538.1,121419.5,163266.5,66.0,16656,64

In [31]:
analysis_deserialization(program_results, "deserialization_with_one_access")

\begin{tabular}{llrrrrrr}
\toprule
 & id & avg_time_taken_net & min_time_net & max_time_net & buffer_size_net & flash_text_net & static_ram_net \\
\midrule
0 & nakedbytes_deserialization_with_one_access & 388.800000 & 335.500000 & 491.500000 & 72.000000 & 714 & 8 \\
1 & flatbuffers_deserialization_with_one_access & 5214.000000 & 4724.500000 & 5995.500000 & 108.000000 & 1974 & 16 \\
2 & protobuf_deserialization_with_one_access & 39176.900000 & 35808.500000 & 44233.500000 & 66.000000 & 2761313 & 153884 \\
3 & nanopb_deserialization_with_one_access & 133113.900000 & 123093.500000 & 141963.500000 & 66.000000 & 17302 & 72 \\
\bottomrule
\end{tabular}

,id,avg_time_taken_net,min_time_net,max_time_net,buffer_size_net,flash_text_net,static_ram_net
0,nakedbytes_deserialization_with_one_access,388.8,335.5,491.5,72.0,714,8
1,flatbuffers_deserialization_with_one_access,5214.0,4724.5,5995.5,108.0,1974,16
2,protobuf_deserialization_with_one_access,39176.9,35808.5,44233.5,66.0,2761313,153884
3,nanopb_deserialization_with_one_access,133113.9,123093.5,141963.5,66.0,17302,72

In [32]:
analysis_deserialization(program_results, "deserialization_with_all_access")

\begin{tabular}{llrrrrrr}
\toprule
 & id & avg_time_taken_net & min_time_net & max_time_net & buffer_size_net & flash_text_net & static_ram_net \\
\midrule
0 & nakedbytes_deserialization_with_all_access & 2591.200000 & 2240.500000 & 3556.500000 & 72.000000 & 2922 & 16 \\
1 & flatbuffers_deserialization_with_all_access & 35743.300000 & 33650.500000 & 38054.500000 & 108.000000 & 4473 & 24 \\
2 & protobuf_deserialization_with_all_access & 52519.500000 & 47016.500000 & 61063.500000 & 66.000000 & 2763346 & 153892 \\
3 & nanopb_deserialization_with_all_access & 149413.400000 & 125586.500000 & 218156.500000 & 66.000000 & 18621 & 72 \\
\bottomrule
\end{tabular}

,id,avg_time_taken_net,min_time_net,max_time_net,buffer_size_net,flash_text_net,static_ram_net
0,nakedbytes_deserialization_with_all_access,2591.2,2240.5,3556.5,72.0,2922,16
1,flatbuffers_deserialization_with_all_access,35743.3,33650.5,38054.5,108.0,4473,24
2,protobuf_deserialization_with_all_access,52519.5,47016.5,61063.5,66.0,2763346,153892
3,nanopb_deserialization_with_all_access,149413.4,125586.5,218156.5,66.0,18621,72

In [33]:
analysis_serialization(program_results, "serialization_primitive")

\begin{tabular}{llrrrrrr}
\toprule
 & id & avg_time_taken_net & min_time_net & max_time_net & buffer_size_net & flash_text_net & static_ram_net \\
\midrule
0 & nakedbytes_serialization_primitives & 9510.300000 & 8892.200000 & 10864.200000 & 36.000000 & 4006 & 32 \\
1 & flatbuffers_serialization_primitives & 125199.400000 & 117136.200000 & 132531.200000 & 56.000000 & 21675 & 256 \\
2 & protobuf_serialization_primitives & 73964.100000 & 71275.200000 & 77237.200000 & 33.000000 & 2765006 & 153916 \\
3 & nanopb_serialization_primitives & 85983.300000 & 78047.200000 & 100380.200000 & 33.000000 & 27044 & 72 \\
\bottomrule
\end{tabular}

,id,avg_time_taken_net,min_time_net,max_time_net,buffer_size_net,flash_text_net,static_ram_net
0,nakedbytes_serialization_primitives,9510.3,8892.2,10864.2,36.0,4006,32
1,flatbuffers_serialization_primitives,125199.4,117136.2,132531.2,56.0,21675,256
2,protobuf_serialization_primitives,73964.1,71275.2,77237.2,33.0,2765006,153916
3,nanopb_serialization_primitives,85983.3,78047.2,100380.2,33.0,27044,72

In [34]:
analysis_serialization(program_results, "serialization_all")

\begin{tabular}{llrrrrrr}
\toprule
 & id & avg_time_taken_net & min_time_net & max_time_net & buffer_size_net & flash_text_net & static_ram_net \\
\midrule
0 & nakedbytes_serialization_all & 17256.300000 & 14269.200000 & 24661.200000 & 71.000000 & 5284 & 56 \\
1 & flatbuffers_serialization_all & 195819.300000 & 177275.200000 & 220940.200000 & 108.000000 & 23261 & 264 \\
2 & protobuf_serialization_all & 72620.200000 & 65887.200000 & 80949.200000 & 66.000000 & 2766331 & 153924 \\
3 & nanopb_serialization_all & 102485.700000 & 97585.200000 & 109016.200000 & 66.000000 & 27446 & 72 \\
\bottomrule
\end{tabular}

,id,avg_time_taken_net,min_time_net,max_time_net,buffer_size_net,flash_text_net,static_ram_net
0,nakedbytes_serialization_all,17256.3,14269.2,24661.2,71.0,5284,56
1,flatbuffers_serialization_all,195819.3,177275.2,220940.2,108.0,23261,264
2,protobuf_serialization_all,72620.2,65887.2,80949.2,66.0,2766331,153924
3,nanopb_serialization_all,102485.7,97585.2,109016.2,66.0,27446,72